config/routes.rb
Rails.application.routes.draw do
  get 'recipe_food/destroy'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "recipes#show_public_recipes"
  
  resources :foods, only: %i[index create destroy]
  resources :recipes, only: %i[new create index show destroy update]
  resources :recipe_foods, only: %i[destroy create]
  get 'public_recipes', to: 'recipes#show_public_recipes'
  get 'general_shopping_list', to: 'users#index', as: 'shopping_list'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :preparation_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :cooking_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

  # Internal: Calculates total cost of foods.
  #
  # Iterates through the entire foods list and calculates
  # the total price by incrementing an acumulator variable.
  #
  # No Parameters.
  #
  # Returns an integer with the total price.

  def total_cost
    total_price = 0
    ingredients = recipe_foods.includes(:food)
    ingredients.each do |ingredient|
      total_price += ingredient.total_price
    end
    total_price
  end

  # Internal: Retrieves all the public recipes.
  #
  # Makes a query that fetches all the public recipes ordered by creating date
  # and includes the food collection. This operation avoids N+1 queries.
  #
  # No parameters.
  #
  # Returns an array of recipes.

  def self.public_recipes
    all.where(public: true).order(created_at: :desc).includes(:foods)
  end

  # Internal: Calculates total ingredient items.
  #
  # No parameters.
  #
  # Returns an integer with the length of food collection

  def total_ingredients
    foods.length
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show show_public_recipes]

  def new
    recipe = Recipe.new
    respond_to do |format|
      format.html { render :new, locals: { recipe: } }
    end
  end

  def index
    @recipes = current_user.fetch_recipes
  end

  def create
    recipe = Recipe.new(recipe_params)
    recipe.user = current_user
    respond_to do |format|
      format.html do
        if recipe.save
          flash[:success] = 'Recipe was succesfully created'
          redirect_to action: :index
        else
          flash.now[:alert] = 'Wrond Value. Please make sure you filled all inputs'
          render :new, status: 422, locals: { recipe: }
        end
      end
    end
  end

  def show
    @recipe = Recipe.includes(:recipe_foods, :foods).find(params[:id])
    @items = RecipeFood.includes(:recipe, :food).where(recipe_id: params[:id])
  end

  def destroy
    id = params[:id]
    Recipe.destroy(id)
    flash[:alert] = 'Recipe succesfully deleted'
    redirect_back(fallback_location: root_path)
  end

  def show_public_recipes
    @recipes = Recipe.public_recipes
  end

  def update
    id = params[:id]
    respond_to do |format|
      format.html do
        public_val = !Recipe.find(id).public
        redirect_back(fallback_location: '/') if Recipe.update(id, public: public_val)
      end
    end
  end

  private

  # Internal: Define strong parameters for recipe creation.
  #
  # Retrieves values from the form and converts string data type to integer for
  # preparation_time and cooking_time properties, since the database requires it for
  # its instantiation.
  #
  # No examples
  #
  # Returns a hash of parameters

  def recipe_params
    response = params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
    response[:preparation_time] = response[:preparation_time].to_i
    response[:cooking_time] = response[:cooking_time].to_i
    response
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_add_ingredient_form.html.erb
<%= form_with(model: food, url: recipe_foods_url, scope: :ingredient, class: 'text-black') do |f| %>
  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Add ingredient</h5>
  </div>
  <div class="modal-body">
    <% if food.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(food.errors.count, 'error') %> prohibited this ingredients from being saved:</h2>

        <ul>
          <% food.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :ingredient %><br />
      <%= f.search_field :ingredient, autofocus: true, autocomplete: "ingredient", list: 'foods' %>
      <datalist id="foods">
        <% Food.all.each do |food| %>
          <option value="<%= food.name %>">
        <% end %>
      <datalist>
    </div>

    <div class="form-group">
      <%= f.label :quantity %><br />
      <%= f.number_field :quantity, autofocus: true, autocomplete: "quantity" %>
    </div>

    <div class="form-group">
      <%= f.hidden_field :recipe, value: recipe_id %>
    </div>
  </div>

  <div class="modal-footer justify-content-start">
    <% if food.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', food, method: :delete, class: 'text_danger', data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <%= f.submit class: 'btn btn-primary float-left' %>
  </div>
<% end %>

app/views/recipes/index.html.erb
<div class="container-fluid d-flex flex-column align-items-center pt-5">
  <%= link_to 'Add Recipe', new_recipe_path, class: "btn btn-secondary btn-small" %>
  <ul class="container">
    <% @recipes.each do |recipe| %>
      <li id= "recipe-card: <%=recipe.id%>" class="container-fluid border border-2 border-primary mb-4 mt-3 p-4 position-relative" >
        <%= link_to recipe_path(id: recipe.id), id: "Recipe: #{recipe.id}", class: "recipe d-flex justify-content-between" do %>
          <h2 class="fs-1 text-white fw-semibold"> <%= recipe.name %> </h2>
          <p class="text-white fs-5 pt-2"> <%= truncate(recipe.description, :length => 300) %> </p>
        <% end %>
        <%= button_to 'Remove', recipe_path(id: recipe.id), method: :delete, class: "btn btn-danger" %>
      <li>
    <% end %>
  </ul>
</div>

app/views/recipes/new.html.erb
<div class="container-fluid d-flex justify-content-center align-items-center p-5">
  <%= form_with model: recipe, class: "mt-5 d-flex flex-column align-items-center container", method: :post do |f| %>
    <div class="d-flex flex-column align-items-center mt-3 w-100">
      <%= f.label :name, class: "text-primary fs-5" %>
      <%= f.text_field :name, class: "w-75 border border-secondary p-2" %>
    </div>
    <div class="d-flex flex-column align-items-center mt-3 w-100">
      <%= f.label :preparation_time, class: "text-primary fs-5" %>
      <%= f.number_field :preparation_time, class: "w-25 border border-secondary p-2" %>
    </div>
    <div class="d-flex flex-column align-items-center mt-3 w-100">
      <%= f.label :cooking_time, class: "text-primary fs-5" %>
      <%= f.number_field :cooking_time, class: "w-25 border border-secondary p-2" %>
    </div>
    <div class="d-flex flex-column align-items-center mt-3 w-100">
      <%= f.label :description, class: "text-primary fs-5" %>
      <%= f.text_area :description, rows: 14, class: "w-75 border border-secondary p-2" %>
    </div>
    <div class="form-check form-switch d-flex align-items-center justify-content-center gap-5 mt-3 w-100">
      <%= f.label :public, class: "text-primary fs-5" %>
      <%= f.check_box :public, class: "form-check-input" %>
    </div>
    <%= f.submit 'Create Recipe', class: "mt-3 btn btn-primary w-75" %>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="recipe text-white p-5">
  <h2 class="display-5 text-center"><%= @recipe.name %></h2>
  <div class="d-flex justify-content-between">
    <div>
      <h3>Preparation time: <%= @recipe.preparation_time %></h3>
      <h3>Cooking time: <%= @recipe.cooking_time %></h3>
      <p><%= @recipe.description %></p>
    </div>
    <% if can? :manage, @recipe %>
      <div>
        <%= form_with(model: @recipe, url: recipe_path(@recipe.id), method: :put, class: 'form-check form-switch') do |f| %>
          <%= f.label :public, class: "form-check-label" %>
          <button type="submit" class="transparent">
            <label class="switch align-middle">
              <%= check_box_tag "public", :public, @recipe.public %>
              <span class="slider round"></span>
            </label>
          </button>
        <% end %>
      </div>
    <% end %>
  </div>
  <% if can? :manage, @recipe %>
    <div class="d-flex justify-content-between">
      <%= button_to 'Generate shopping list', '#', class: 'btn btn-secondary text-white' %>
      <button type="button" class="btn btn-secondary text-white" data-bs-toggle="modal" data-bs-target="#newIngredientModal">
        Add ingredient
      </button>

      <div class="modal fade" id="newIngredientModal" tabindex="-1" aria-labelledby="newIngredientModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <%= render partial: 'recipes/add_ingredient_form', locals: { food: RecipeFood.new, recipe_id: params[:id] }%>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <%= render partial: 'shared/table', locals: {
    columns: ['Food', 'Quantity', 'Value', 'Actions'],
    values: @items.map {
      |item| [
        item.food.name, "#{item.quantity} #{item.food.measurement_unit}",
        item.food.price.to_s + '$',
        [{label: 'Modify', path: '#'}, { label: 'Remove', path: recipe_food_path(item.id), method: :delete }]
      ] 
    } 
  }%>
</div>

app/views/recipes/show_public_recipes.html.erb
<div>
  <h1 class="text-white display-2"> Public Recipes </h1>
  <ul>
    <% @recipes.each do |recipe| %>
      <li id= "recipe-card: <%=recipe.id%>" class="container-fluid border border-2 border-primary mb-4 mt-3 p-4 position-relative" >
        <%= link_to recipe_path(id: recipe.id), id: "Recipe: #{recipe.id}", class: "recipe d-flex justify-content-between px-5 flex-wrap" do %>
          <div class="min-w-25">
            <h2 class="fs-1 text-white fw-semibold"> <%= recipe.name %> </h2>
            <p class="text-white fs-5 pt-2">By: <%= recipe.user.name %> </p>
          </div>
          <div class="min-w-25">
            <p class="text-white fs-5 pt-2"> Total food items: <%= recipe.total_ingredients %> </p>
            <p class="text-white fs-5 pt-2"> Total price: <%= recipe.total_cost %> </p>
          </div>
        <% end %>
        <% if can? :destroy, recipe %>
          <%= button_to 'Remove', recipe_path(id: recipe.id), method: :delete, class: "btn btn-danger ms-5" %>
        <% end %>
      </li>
    <% end %> 
  </ul>
</div>