config/routes.rb
Rails.application.routes.draw do
  get 'recipe_food/destroy'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "recipes#show_public_recipes"
  
  resources :foods, only: %i[index create destroy]
  resources :recipes, only: %i[new create index show destroy update]
  resources :recipe_foods, only: %i[destroy create]
  get 'public_recipes', to: 'recipes#show_public_recipes'
  get 'general_shopping_list', to: 'users#index', as: 'shopping_list'
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark navbar-expand-lg bg-dark shadow">
  <div class="container-fluid">
    <%= link_to 'Recipes', '/', class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Home', '/', class: "nav-link #{ current_page?('/') ? 'active' : '' }" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Food', foods_path, class: "nav-link #{ current_page?(foods_path) ? 'active' : '' }" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Recipes', recipes_path, class: "nav-link #{ current_page?(recipes_path) ? 'active' : '' }" %>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav mb-2 mb-lg-0" >
        <% if user_signed_in? %>
          <li>
            <%= link_to shopping_list_path, class: 'btn btn-outline-secondary d-flex me-3' do %>
              <i class="bi bi-cart text-white pe-2"></i>
              Shopping List
            <% end %>
          </li>
          <li>
            <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: "btn btn-outline-primary" %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Log in', new_user_session_path, class: "btn btn-outline-primary" %>
          </li>  
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_table.html.erb
<table class="table shadow table-dark table-striped">
  <thead>
    <tr>
      <% columns.each do |column|%>
        <th scope="col"><%= column %></th>
      <% end %>
    </tr>
  </thead>
  <tbody class="foods-table">
    <% values.each do |item| %>
      <tr>
        <th scope="row"><%= item[0] %></th>
        <td><%= item[1] %></td>
        <td><%= item[2] %></td>
        <td>
          <% item[3].each do |button| %>
            <%= button_to button[:label], button[:path], class: 'link-secondary transparent me-4', method: button[:method] %>
          <% end %>        
        </td>
      </tr>
    <% end %>
  </tbody>
</table>