config/routes.rb
Rails.application.routes.draw do
  get 'recipe_food/destroy'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "recipes#show_public_recipes"
  
  resources :foods, only: %i[index create destroy]
  resources :recipes, only: %i[new create index show destroy update]
  resources :recipe_foods, only: %i[destroy create]
  get 'public_recipes', to: 'recipes#show_public_recipes'
  get 'general_shopping_list', to: 'users#index', as: 'shopping_list'
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  # /foods
  def index
    @items = current_user.foods.order(created_at: :desc)
  end

  # /foods (post)
  def create
    food = Food.new(foods_params)
    p food
    food.user = current_user

    if food.save
      flash[:success] = 'Food item has been created'
    else
      flash[:alert] = 'Food item could not be saved'
    end
    redirect_to foods_path
  end

  # /foods/:id (delete)
  def destroy
    if Food.find(params[:id]).destroy
      flash[:success] = 'Food item has been deleted'
    else
      flash[:alert] = 'Food item could not be deleted'
    end
    redirect_back fallback_location: '/'
  end

  # public: gets the most recent posts from the database
  #
  # returns an array of at most 15 posts
  def most_recent_added
    Food.order(id: :desc).limit(15)
  end

  private

  def foods_params
    par = params[:foods].permit(:name, :measurement_unit, :price)
    par[:price] = par[:price].to_f
    par
  end
end

app/helpers/food_helper.rb
module FoodHelper
end

app/views/foods/_form.html.erb
<%= form_with(model: food, url: foods_url, scope: :foods, class: 'text-white' ) do |f| %>
  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Create food</h5>
  </div>
  <div class="modal-body">
    <% if food.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(food.errors.count, 'error') %> prohibited this ingredients from being saved:</h2>

        <ul>
          <% food.erros.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="form-group">
      <%= f.label :measurement_unit %><br />
      <%= f.text_field :measurement_unit , autofocus: true, autocomplete: "measurement unit " %>
    </div>

    <div class="form-group">
      <%= f.label :price %><br />
      <%= f.text_field :price, autofocus: true, autocomplete: "price" %>
    </div>
  </div>
  <div class="modal-footer justify-content-start">
    <% if food.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', food, method: :delete, class: 'text_danger', data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= f.submit class: 'btn btn-primary float-left' %>
  </div>
<% end %>

app/views/foods/index.html.erb
<section class="container-fluid d-flex flex-column p-5 gap-3 bg-dark foods-section">
  <%= render partial: 'foods/form', locals: { food: Food.new } %>
  <div class="foods-table">
  <%= render partial: 'shared/table', locals: {
    columns: ['Food', 'measurement unit', 'Value', 'Actions'],
    values: @items.map {
      |item| [
        item.name,
        item.measurement_unit,
        item.price.to_s + '$',
        [{label: 'Remove', path: food_path(item.id), method: :delete}]
      ] 
    } 
  }%>
  </div>
</section>